- name: Install dependencies
  package:
    name: sudo
    state: present

- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name }}"
    groups: sudo
    append: yes
    state: present
    shell: /bin/bash
  loop: '{{ users }}'
  when: ansible_os_family == "Debian"

- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name }}"
    groups: wheel
    append: yes
    state: present
    shell: /bin/bash
  loop: '{{ users }}'
  when: ansible_os_family == "RedHat"

- name: Add keys to users.
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_keys }}"
  loop: '{{ users }}'

- name: Allow privilege escalation without password.
  lineinfile:
    dest: /etc/sudoers.d/30-{{ item.username }}
    owner: root
    group: root
    mode: 0440
    line: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
    state: present
    create: yes
    validate: 'visudo -cf %s'
  loop: "{{ users }}"
