- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name }}"
    groups: sudo
    append: yes
    state: present
    shell: /bin/bash
  loop: '{{ users }}'
  when: ansible_os_family == "Debian"

- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.name }}"
    append: yes
    state: present
    shell: /bin/bash
  loop: '{{ users }}'
  when: ansible_os_family == "RedHat"

- name: Add keys to users.
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.public_keys }}"
  loop: '{{ users }}'

- name: Allow privilege escalation without password.
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo ALL\='
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  when: ansible_os_family == "Debian"
