---

- name: Install the prerequisite packages for the MOTD scripts.
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - lsb-release

- name: Create the destination folder.
  file:
    state: directory
    path: /etc/update-motd.d/

- name: Create the correct template files.
  template:
    src: "{{ item }}"
    dest: /etc/update-motd.d/
    mode: "a=x"
  with_items:
    - 00-header
    - 10-sysinfo
    - 90-footer
