autocmd BufNewFile,BufRead * setlocal formatoptions-=r

set showmode
set showcmd

filetype plugin indent off
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set list listchars=tab:\ \ ,trail:·

set scrolloff=8
set sidescrolloff=15
set sidescroll=1

set ignorecase
set smartcase
