---
- hosts: ubuntu
  become: yes
  roles:
    - init
    - update
    - common-ubuntu
    - linux-motd
    - update

- hosts: debian
  become: yes
  roles:
    - init
    - update
    - common-debian
    - linux-motd
    - update

- hosts: vm
  become: yes
  roles:
    - vm

- hosts: vpn
  become: yes
  roles:
    - vpn
